version: "3.1"

services:
  blog_port_evandro:
    container_name: blog_port_evandro
    hostname: blog_port_evandro
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog_port_evandro
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgresData/postgresonly/blog_port_evandro:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
